// CLEARWEB — Content Script
const AI_RULES = {
  siteSelectors: {
    "google.com": [".YzccAd", ".M8OgIe", "#kp-wp-tab-overview", "[data-attrid='SGEModule']", ".aiOverview", "ai-overview", ".WQFNbb"],
    "bing.com": ["#b_sydConvCont", "#copilot-chat", ".copilot-chat-container", "#coptMessageContainer", ".b_ai_container"],
    "stackoverflow.com": [".js-gpt-answer", ".s-sidebarwidget--ai", "[data-campaign='ai-assistant']"],
    "reddit.com": [".AIsummary", "[data-testid='ai-summary']", ".ai-answer-container"],
    "github.com": [".copilot-chat-panel", "#copilot-button-positioner", ".js-copilot-entrypoint"],
    "linkedin.com": [".ai-disclaimer", "[data-view-name='AI_MESSAGE_DISCLAIMER']", ".artdeco-ai-promo"],
    "youtube.com": ["#structured-description-ai-generated", "ytd-structured-description-content-renderer[is-ai-generated]"],
    "amazon.com": ["#product-summary-lazy-widget", "[data-feature-name='aiReviewsSummary']", ".cr-lighthouse-terms"]
  },
  chatbotSelectors: [
    "#intercom-container", "#intercom-frame", ".intercom-lightweight-app",
    "#drift-widget-container", "#drift-frame-controller",
    "#tidio-chat", "#tidio-chat-iframe",
    "#launcher", "iframe[title='Button to launch messaging window']",
    "#freshworks-container", "#freshchat-container",
    "#hubspot-messages-iframe-container",
    ".crisp-client", "#crisp-chatbox",
    "#chat-widget-container",
    "#olark-wrapper", "#tawkchat-container",
    "#gorgias-chat-container", "#reamaze-widget"
  ],
  universalPatterns: [
    "ai-overview", "ai-answer", "ai-summary", "ai-generated",
    "ai-response", "ai-widget", "ai-assistant", "ai-chatbot",
    "gpt-answer", "copilot-", "gemini-", "bard-"
  ],
  textKeywords: [
    "AI-generated", "Generated by AI", "Powered by AI", "AI Overview",
    "Ask AI", "AI answer", "AI summary", "Summarized by AI",
    "AI wrote this", "Created with AI", "Written by AI",
    "This answer was generated", "Generative AI"
  ]
};

let isEnabled = true;
let removedCount = 0;
const removedElements = new WeakSet();

function getHostname() { return window.location.hostname.replace(/^www\./, ""); }

function hideElement(el, reason) {
  if (removedElements.has(el)) return;
  el.style.setProperty("display", "none", "important");
  el.setAttribute("data-clearweb-removed", reason);
  removedElements.add(el);
  removedCount++;
}

function removeSiteSpecific() {
  const hostname = getHostname();
  const matchingKey = Object.keys(AI_RULES.siteSelectors).find(site => hostname === site || hostname.endsWith("." + site));
  if (!matchingKey) return;
  AI_RULES.siteSelectors[matchingKey].forEach(selector => {
    try { document.querySelectorAll(selector).forEach(el => hideElement(el, "site-specific")); } catch (e) {}
  });
}

function removeChatbots() {
  AI_RULES.chatbotSelectors.forEach(selector => {
    try { document.querySelectorAll(selector).forEach(el => hideElement(el, "chatbot")); } catch (e) {}
  });
}

function removeByPattern() {
  document.querySelectorAll("[class], [id]").forEach(el => {
    const classStr = (el.className && typeof el.className === "string") ? el.className.toLowerCase() : "";
    const idStr = el.id ? el.id.toLowerCase() : "";
    const combined = classStr + " " + idStr;
    if (AI_RULES.universalPatterns.some(p => combined.includes(p.toLowerCase()))) hideElement(el, "pattern");
  });
}

function removeByKeyword() {
  document.querySelectorAll("div, section, aside, article, [role='complementary'], [role='region']").forEach(el => {
    if (el.children.length > 20) return;
    const text = el.innerText || "";
    if (AI_RULES.textKeywords.some(kw => text.includes(kw))) hideElement(el, "keyword");
  });
}

function runRemoval() {
  if (!isEnabled) return;
  removedCount = 0;
  removeSiteSpecific();
  removeChatbots();
  removeByPattern();
  removeByKeyword();
  chrome.runtime.sendMessage({ type: "REMOVED_COUNT", count: removedCount }).catch(() => {});
}

const observer = new MutationObserver(() => { if (isEnabled) runRemoval(); });
observer.observe(document.body, { childList: true, subtree: true });

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === "SET_ENABLED") {
    isEnabled = message.enabled;
    if (!isEnabled) {
      document.querySelectorAll("[data-clearweb-removed]").forEach(el => {
        el.style.removeProperty("display");
        el.removeAttribute("data-clearweb-removed");
      });
      removedCount = 0;
    } else { runRemoval(); }
    sendResponse({ ok: true });
  }
  if (message.type === "GET_COUNT") sendResponse({ count: removedCount });
});

chrome.storage.sync.get(["enabled"], (result) => {
  isEnabled = result.enabled !== false;
  runRemoval();
});